/**
 * Phase 16 — Demo Forecast Data & Timeline Generator
 * SIH26076 · PersonalizedMAUSAM
 *
 * Deterministic multi-period forecast timelines for prototype demo scenarios.
 * Always explicitly attributes demo forecasts as prototype data.
 */

import type { DemoScenarioId, WeatherData } from '../types';
import type { ForecastData, ForecastPeriod } from '../types/forecast';

export const DEMO_FORECAST_MAP: Record<DemoScenarioId, ForecastPeriod[]> = {
  NORMAL: [
    {
      id: 'norm_p0',
      timestamp: 'Now',
      displayTime: 'Now',
      temperature: 26,
      feelsLike: 26,
      condition: 'partly_cloudy',
      humidity: 52,
      windSpeed: 12,
      windDirection: 'NW',
      rainProbability: 10,
      rainfall: 0,
      uvIndex: 4,
      visibility: 9,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Optimal conditions for outdoor activities and morning commute.',
      badge: 'Comfortable',
    },
    {
      id: 'norm_p1',
      timestamp: '+3 hrs',
      displayTime: '+3 hrs (1:00 PM)',
      temperature: 28,
      feelsLike: 29,
      condition: 'partly_cloudy',
      humidity: 48,
      windSpeed: 14,
      windDirection: 'NW',
      rainProbability: 15,
      rainfall: 0,
      uvIndex: 6,
      visibility: 10,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Moderate sun exposure. Mild UV window during early afternoon.',
      badge: 'Mild Sun',
    },
    {
      id: 'norm_p2',
      timestamp: '+6 hrs',
      displayTime: '+6 hrs (4:00 PM)',
      temperature: 27,
      feelsLike: 27,
      condition: 'clear',
      humidity: 50,
      windSpeed: 13,
      windDirection: 'WNW',
      rainProbability: 10,
      rainfall: 0,
      uvIndex: 3,
      visibility: 10,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Favorable temperature for outdoor running, errands, and transit.',
      badge: 'Favorable',
    },
    {
      id: 'norm_p3',
      timestamp: '+9 hrs',
      displayTime: '+9 hrs (7:00 PM)',
      temperature: 24,
      feelsLike: 24,
      condition: 'clear',
      humidity: 58,
      windSpeed: 10,
      windDirection: 'NW',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 0,
      visibility: 9,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Pleasant evening twilight. Suitable for gatherings and dining.',
      badge: 'Pleasant',
    },
    {
      id: 'norm_p4',
      timestamp: '+12 hrs',
      displayTime: '+12 hrs (10:00 PM)',
      temperature: 22,
      feelsLike: 22,
      condition: 'clear',
      humidity: 62,
      windSpeed: 8,
      windDirection: 'N',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 0,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Cool night air. Calm conditions across the district.',
      badge: 'Calm',
    },
  ],

  HOT_SUNNY: [
    {
      id: 'hot_p0',
      timestamp: 'Now',
      displayTime: 'Now',
      temperature: 39,
      feelsLike: 43,
      condition: 'heat',
      humidity: 45,
      windSpeed: 14,
      windDirection: 'NW',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 10,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Elevated heat index. Shift cardio workouts indoors and maintain electrolyte hydration.',
      badge: 'Extreme Heat',
    },
    {
      id: 'hot_p1',
      timestamp: '+3 hrs',
      displayTime: '+3 hrs (1:00 PM)',
      temperature: 41,
      feelsLike: 45,
      condition: 'heat',
      humidity: 40,
      windSpeed: 16,
      windDirection: 'WNW',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 11,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Peak thermal load. Avoid prolonged direct sun exposure between 12 PM - 3 PM.',
      badge: 'Peak Heat',
    },
    {
      id: 'hot_p2',
      timestamp: '+6 hrs',
      displayTime: '+6 hrs (4:00 PM)',
      temperature: 38,
      feelsLike: 41,
      condition: 'clear',
      humidity: 44,
      windSpeed: 15,
      windDirection: 'W',
      rainProbability: 10,
      rainfall: 0,
      uvIndex: 5,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Surface temperatures remain high. Exercise caution with vehicle cooling and transit.',
      badge: 'Warm Evening',
    },
    {
      id: 'hot_p3',
      timestamp: '+9 hrs',
      displayTime: '+9 hrs (7:00 PM)',
      temperature: 33,
      feelsLike: 35,
      condition: 'clear',
      humidity: 52,
      windSpeed: 12,
      windDirection: 'W',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 0,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Post-sunset cooling window. Preferred period for outdoor walking and exercise.',
      badge: 'Cooling Window',
    },
    {
      id: 'hot_p4',
      timestamp: '+12 hrs',
      displayTime: '+12 hrs (10:00 PM)',
      temperature: 30,
      feelsLike: 32,
      condition: 'clear',
      humidity: 58,
      windSpeed: 10,
      windDirection: 'NW',
      rainProbability: 5,
      rainfall: 0,
      uvIndex: 0,
      visibility: 8,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Warm nocturnal baseline. Ensure adequate home ventilation.',
      badge: 'Warm Night',
    },
  ],

  RAINY: [
    {
      id: 'rain_p0',
      timestamp: 'Now',
      displayTime: 'Now',
      temperature: 24,
      feelsLike: 25,
      condition: 'rain',
      humidity: 92,
      windSpeed: 24,
      windDirection: 'SW',
      rainProbability: 85,
      rainfall: 28,
      uvIndex: 2,
      visibility: 4,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Continuous active precipitation. Waterlogging likely on low-lying roads. Carry rain gear.',
      badge: 'Heavy Rain',
    },
    {
      id: 'rain_p1',
      timestamp: '+3 hrs',
      displayTime: '+3 hrs (1:00 PM)',
      temperature: 23,
      feelsLike: 24,
      condition: 'thunderstorm',
      humidity: 95,
      windSpeed: 28,
      windDirection: 'SW',
      rainProbability: 95,
      rainfall: 35,
      uvIndex: 1,
      visibility: 3,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Intense convective downpours. Postpone non-urgent road transit and outdoor events.',
      badge: 'Thunderstorm',
    },
    {
      id: 'rain_p2',
      timestamp: '+6 hrs',
      displayTime: '+6 hrs (4:00 PM)',
      temperature: 23,
      feelsLike: 24,
      condition: 'rain',
      humidity: 90,
      windSpeed: 22,
      windDirection: 'WSW',
      rainProbability: 80,
      rainfall: 18,
      uvIndex: 1,
      visibility: 5,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Intermittent moderate showers continuing. Commute delays expected across major junctions.',
      badge: 'Moderate Rain',
    },
    {
      id: 'rain_p3',
      timestamp: '+9 hrs',
      displayTime: '+9 hrs (7:00 PM)',
      temperature: 22,
      feelsLike: 23,
      condition: 'rain',
      humidity: 88,
      windSpeed: 18,
      windDirection: 'W',
      rainProbability: 60,
      rainfall: 8,
      uvIndex: 0,
      visibility: 6,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Tapering showers by late evening. Roads remain slick with reduced traction.',
      badge: 'Light Showers',
    },
    {
      id: 'rain_p4',
      timestamp: '+12 hrs',
      displayTime: '+12 hrs (10:00 PM)',
      temperature: 21,
      feelsLike: 22,
      condition: 'cloudy',
      humidity: 86,
      windSpeed: 14,
      windDirection: 'WNW',
      rainProbability: 40,
      rainfall: 2,
      uvIndex: 0,
      visibility: 6,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Overcast skies with lingering moisture. High humidity persists.',
      badge: 'Overcast',
    },
  ],

  HIGH_UV: [
    {
      id: 'uv_p0',
      timestamp: 'Now',
      displayTime: 'Now',
      temperature: 32,
      feelsLike: 35,
      condition: 'clear',
      humidity: 45,
      windSpeed: 12,
      windDirection: 'NW',
      rainProbability: 0,
      rainfall: 0,
      uvIndex: 11,
      visibility: 10,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Extreme UV Index 11. Apply broad-spectrum SPF 50+, wear protective eyewear and wide-brim hats.',
      badge: 'Extreme UV',
    },
    {
      id: 'uv_p1',
      timestamp: '+3 hrs',
      displayTime: '+3 hrs (1:00 PM)',
      temperature: 34,
      feelsLike: 37,
      condition: 'clear',
      humidity: 42,
      windSpeed: 14,
      windDirection: 'NW',
      rainProbability: 0,
      rainfall: 0,
      uvIndex: 11,
      visibility: 10,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Maximum solar radiation. Unprotected skin damage occurs rapidly in under 15 minutes.',
      badge: 'Peak UV',
    },
    {
      id: 'uv_p2',
      timestamp: '+6 hrs',
      displayTime: '+6 hrs (4:00 PM)',
      temperature: 31,
      feelsLike: 33,
      condition: 'clear',
      humidity: 48,
      windSpeed: 12,
      windDirection: 'WNW',
      rainProbability: 0,
      rainfall: 0,
      uvIndex: 5,
      visibility: 10,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Solar intensity declining to moderate. Safe window for outdoor family walks.',
      badge: 'Moderate UV',
    },
    {
      id: 'uv_p3',
      timestamp: '+9 hrs',
      displayTime: '+9 hrs (7:00 PM)',
      temperature: 27,
      feelsLike: 28,
      condition: 'clear',
      humidity: 55,
      windSpeed: 10,
      windDirection: 'NW',
      rainProbability: 0,
      rainfall: 0,
      uvIndex: 0,
      visibility: 9,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Zero solar radiation post-sunset. Ideal window for evening outdoor runs and cycling.',
      badge: 'Safe Window',
    },
    {
      id: 'uv_p4',
      timestamp: '+12 hrs',
      displayTime: '+12 hrs (10:00 PM)',
      temperature: 25,
      feelsLike: 25,
      condition: 'clear',
      humidity: 60,
      windSpeed: 8,
      windDirection: 'N',
      rainProbability: 0,
      rainfall: 0,
      uvIndex: 0,
      visibility: 9,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Clear night. Comfortable ambient conditions across all zones.',
      badge: 'Clear Night',
    },
  ],

  SEVERE_WEATHER: [
    {
      id: 'sev_p0',
      timestamp: 'Now',
      displayTime: 'Now',
      temperature: 28,
      feelsLike: 31,
      condition: 'severe',
      humidity: 88,
      windSpeed: 58,
      windDirection: 'SW',
      rainProbability: 95,
      rainfall: 45,
      uvIndex: 1,
      visibility: 2,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: '🚨 CRITICAL SAFETY WARNING: Severe cyclonic squall active. Remain indoors away from glass.',
      badge: 'Severe Warning',
    },
    {
      id: 'sev_p1',
      timestamp: '+3 hrs',
      displayTime: '+3 hrs (1:00 PM)',
      temperature: 26,
      feelsLike: 29,
      condition: 'severe',
      humidity: 92,
      windSpeed: 65,
      windDirection: 'SW',
      rainProbability: 100,
      rainfall: 60,
      uvIndex: 0,
      visibility: 1,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Peak storm intensity. Violent wind gusts exceeding 65 km/h. Essential travel only under emergency escort.',
      badge: 'Extreme Squall',
    },
    {
      id: 'sev_p2',
      timestamp: '+6 hrs',
      displayTime: '+6 hrs (4:00 PM)',
      temperature: 25,
      feelsLike: 27,
      condition: 'thunderstorm',
      humidity: 90,
      windSpeed: 45,
      windDirection: 'WSW',
      rainProbability: 85,
      rainfall: 30,
      uvIndex: 1,
      visibility: 3,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Storm eyewall passing. High winds and lightning hazards remain active.',
      badge: 'Storm Subsiding',
    },
    {
      id: 'sev_p3',
      timestamp: '+9 hrs',
      displayTime: '+9 hrs (7:00 PM)',
      temperature: 24,
      feelsLike: 25,
      condition: 'rain',
      humidity: 85,
      windSpeed: 30,
      windDirection: 'W',
      rainProbability: 70,
      rainfall: 15,
      uvIndex: 0,
      visibility: 5,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Wind tapering to advisory levels. Watch for fallen trees and downed cables.',
      badge: 'Advisory Wind',
    },
    {
      id: 'sev_p4',
      timestamp: '+12 hrs',
      displayTime: '+12 hrs (10:00 PM)',
      temperature: 23,
      feelsLike: 24,
      condition: 'cloudy',
      humidity: 82,
      windSpeed: 20,
      windDirection: 'WNW',
      rainProbability: 40,
      rainfall: 4,
      uvIndex: 0,
      visibility: 6,
      availableFields: ['temperature', 'feelsLike', 'condition', 'humidity', 'windSpeed', 'windDirection', 'rainProbability', 'rainfall', 'uvIndex', 'visibility'],
      personalizedNote: 'Post-storm recovery phase. Residual overcast skies.',
      badge: 'Overcast Recovery',
    },
  ],
};

/**
 * Returns prototype demo forecast data for the active location.
 */
export function getDemoForecast(scenarioId: DemoScenarioId, locationName: string): ForecastData {
  const periods = DEMO_FORECAST_MAP[scenarioId] || DEMO_FORECAST_MAP.NORMAL;

  return {
    locationId: locationName.toLowerCase().replace(/\s+/g, '_'),
    locationName,
    source: 'Prototype Demo Forecast • Not live IMD data',
    dataMode: 'demo',
    updatedAt: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }),
    isAvailable: true,
    periods,
  };
}

/**
 * Returns Live IMD forecast structure.
 * Respects strict data integrity rule: NEVER fabricate live forecast periods.
 */
export function getLiveForecast(currentWeather: WeatherData, locationName: string): ForecastData {
  return {
    locationId: locationName.toLowerCase().replace(/\s+/g, '_'),
    locationName,
    source: 'Official IMD Observation',
    dataMode: 'live',
    updatedAt: currentWeather.timestamp || new Date().toISOString(),
    isAvailable: false,
    unavailableReason: 'Forecast details are not currently available from the connected IMD feed. Current weather observations remain active.',
    periods: [],
  };
}

/**
 * Returns deterministic best-time window for outdoor activities.
 */
export function getBestTimeWindow(
  forecast: ForecastData,
  scenarioId?: DemoScenarioId
): { title: string; window: string; reason: string; isAvailable: boolean } {
  if (!forecast.isAvailable || forecast.periods.length === 0) {
    return {
      title: 'Best Activity Window',
      window: 'Unavailable',
      reason: 'Best time cannot be determined from the available forecast data.',
      isAvailable: false,
    };
  }

  if (scenarioId === 'HOT_SUNNY') {
    return {
      title: 'Best Outdoor Window',
      window: 'Evening (After 6:30 PM) or Early Morning',
      reason: 'Temperature drops to 33°C with zero direct UV radiation.',
      isAvailable: true,
    };
  }

  if (scenarioId === 'HIGH_UV') {
    return {
      title: 'Sun-Safe Activity Window',
      window: 'Late Afternoon (+6 hrs / After 4:00 PM)',
      reason: 'UV index declines to moderate levels (≤ 5) with lower sunburn risk.',
      isAvailable: true,
    };
  }

  if (scenarioId === 'RAINY') {
    return {
      title: 'Precipitation Low Window',
      window: 'Late Night (+12 hrs) or Post-Squall',
      reason: 'Rainfall drops to light showers with improved road visibility.',
      isAvailable: true,
    };
  }

  if (scenarioId === 'SEVERE_WEATHER') {
    return {
      title: 'Activity Feasibility Window',
      window: 'No Safe Window Currently',
      reason: 'Severe weather override active. Postpone all outdoor activities until safety clearance.',
      isAvailable: true,
    };
  }

  return {
    title: 'Optimal Outdoor Window',
    window: 'Morning through Afternoon (All Day Favorable)',
    reason: 'Mild temperatures (24°C–28°C) and comfortable humidity throughout the timeline.',
    isAvailable: true,
  };
}
