import type { DemoScenarioId, DemoWeatherScenario } from '../types';

export const DEMO_WEATHER_SCENARIOS: Record<DemoScenarioId, DemoWeatherScenario> = {
  NORMAL: {
    id: 'NORMAL',
    label: 'Normal',
    badge: 'Standard',
    icon: '🌤️',
    description: 'Pleasant temperature, moderate UV, normal visibility',
    weatherData: {
      location: 'Pune',
      timestamp: 'Synthetic Prototype Timestamp • 10:00 AM',
      temperature: 26,
      feelsLike: 26,
      humidity: 55,
      rainfall: 0,
      rainProbability: 15,
      windSpeed: 12,
      windDirection: 'NW',
      uvIndex: 4,
      visibility: 10,
      weatherCondition: 'partly_cloudy',
      sunrise: '06:12 AM',
      sunset: '06:45 PM',
      severity: 'normal',
      summary: 'Comfortable conditions with mild breeze and scattered clouds.',
    },
  },
  HOT_SUNNY: {
    id: 'HOT_SUNNY',
    label: 'Hot & Sunny',
    badge: 'Heat Advisory',
    icon: '☀️',
    description: 'High temperature, elevated heat index, high UV',
    weatherData: {
      location: 'Pune',
      timestamp: 'Synthetic Prototype Timestamp • 02:00 PM',
      temperature: 39,
      feelsLike: 43,
      humidity: 38,
      rainfall: 0,
      rainProbability: 5,
      windSpeed: 14,
      windDirection: 'W',
      uvIndex: 10,
      visibility: 8,
      weatherCondition: 'heat',
      sunrise: '05:58 AM',
      sunset: '07:05 PM',
      severity: 'advisory',
      summary: 'Intense daytime heat with elevated thermal comfort index.',
    },
  },
  RAINY: {
    id: 'RAINY',
    label: 'Rainy',
    badge: 'Wet Weather',
    icon: '🌧️',
    description: 'Heavy precipitation likelihood, overcast sky, reduced visibility',
    weatherData: {
      location: 'Pune',
      timestamp: 'Synthetic Prototype Timestamp • 04:30 PM',
      temperature: 23,
      feelsLike: 24,
      humidity: 92,
      rainfall: 28,
      rainProbability: 85,
      windSpeed: 22,
      windDirection: 'SW',
      uvIndex: 2,
      visibility: 4,
      weatherCondition: 'rain',
      sunrise: '06:18 AM',
      sunset: '06:38 PM',
      severity: 'advisory',
      summary: 'Sustained monsoon showers with wet road surfaces and low cloud base.',
    },
  },
  HIGH_UV: {
    id: 'HIGH_UV',
    label: 'High UV',
    badge: 'Solar Warning',
    icon: '🧴',
    description: 'Very high solar radiation, clear sky, outdoor skin hazard',
    weatherData: {
      location: 'Pune',
      timestamp: 'Synthetic Prototype Timestamp • 12:30 PM',
      temperature: 32,
      feelsLike: 34,
      humidity: 48,
      rainfall: 0,
      rainProbability: 10,
      windSpeed: 10,
      windDirection: 'NE',
      uvIndex: 11,
      visibility: 10,
      weatherCondition: 'clear',
      sunrise: '06:05 AM',
      sunset: '06:52 PM',
      severity: 'advisory',
      summary: 'Clear sunny sky with very high ultraviolet radiation levels.',
    },
  },
  SEVERE_WEATHER: {
    id: 'SEVERE_WEATHER',
    label: 'Severe Weather',
    badge: 'Safety Priority',
    icon: '⛈️',
    description: 'Torrential downpour, severe wind gusts, low visibility',
    weatherData: {
      location: 'Pune',
      timestamp: 'Synthetic Prototype Timestamp • 06:00 PM',
      temperature: 21,
      feelsLike: 19,
      humidity: 96,
      rainfall: 65,
      rainProbability: 95,
      windSpeed: 58,
      windDirection: 'S',
      uvIndex: 1,
      visibility: 1.5,
      weatherCondition: 'severe',
      sunrise: '06:22 AM',
      sunset: '06:31 PM',
      severity: 'severe',
      summary: 'Severe squall line with torrential downpours, strong gale gusts, and reduced road visibility.',
    },
  },
};

export const DEMO_SCENARIO_LIST: DemoWeatherScenario[] = [
  DEMO_WEATHER_SCENARIOS.NORMAL,
  DEMO_WEATHER_SCENARIOS.HOT_SUNNY,
  DEMO_WEATHER_SCENARIOS.RAINY,
  DEMO_WEATHER_SCENARIOS.HIGH_UV,
  DEMO_WEATHER_SCENARIOS.SEVERE_WEATHER,
];

export const getDemoWeatherScenario = (id: DemoScenarioId): DemoWeatherScenario => {
  return DEMO_WEATHER_SCENARIOS[id] || DEMO_WEATHER_SCENARIOS.NORMAL;
};
